name: Generate Protobuf

on:
  push:
    paths:
      - '**.proto'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout proto files
        uses: actions/checkout@v3
        with:
          repository: elliaaan/protos  # ← имя твоего proto-репозитория
          path: protos

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install protoc-gen-go
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest

      - name: Install protoc-gen-go-grpc
        run: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

      - name: Generate Go code
        run: |
          mkdir -p gen/inventory
          mkdir -p gen/order

          protoc --go_out=gen/inventory --go-grpc_out=gen/inventory protos/inventory/*.proto
          protoc --go_out=gen/order --go-grpc_out=gen/order protos/order/*.proto

      - name: Push generated code
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "auto: regenerate proto code"
