name: Generate Proto

on:
  push:
    branches:
      - main
    paths:
      - '**.proto'

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout protos repo
      uses: actions/checkout@v3
      with:
        repository: elliaaan/protos
        path: protos

    - name: Checkout current repo (proto-gen)
      uses: actions/checkout@v3
      with:
        path: proto-gen

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install protoc plugins
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
        echo "${HOME}/go/bin" >> $GITHUB_PATH

    - name: Generate proto files
      run: |
        mkdir -p proto-gen/inventory
        mkdir -p proto-gen/order

        protoc -I=protos/inventory \
          --go_out=proto-gen/inventory \
          --go-grpc_out=proto-gen/inventory \
          protos/inventory/inventory.proto

        protoc -I=protos/order \
          --go_out=proto-gen/order \
          --go-grpc_out=proto-gen/order \
          protos/order/order.proto

    - name: Commit and push generated code
      run: |
        cd proto-gen
        git config user.name "GitHub Actions"
        git config user.email "action@github.com"
        git add .
        git commit -m "chore: auto-generate pb.go files from proto"
        git push
